blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/zerobell-lee/streamlink-dashboard/blob/master/README.md
    about: Read the project documentation
  - name: 💬 Discussions
    url: https://github.com/zerobell-lee/streamlink-dashboard/discussions
    about: Ask questions and discuss ideas with the community